name: Resize photos
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        run: npm install
      - name: Create thumbs and  carousels
        run: node ./scripts/optimize.js
      - name: Commit report
        run: |
          git status
          git config --global user.name 'pntbr'
          git config --global user.email 'stephane@scopyleft.fr'
          git add -f thumbs carousels
          git commit -m "Formate les photos pour les vignettes et les carrousels" --allow-empty
          git push
