name: Resize photos
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        run: npm install
      - name: Create thumbs and  carousels
        run: node ./scripts/optimize.js
      - name: Commit report
        run: |
          git status
